In [14]:
import os
import numpy as np
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [16]:
basedir = os.path.abspath('.') + r'/dataset/cora/'
cites_path = basedir + 'cora.cites'
content_path = basedir + 'cora.content'

In [17]:
raw_cites = pd.read_csv(cites_path, sep = '\t', header = None)
raw_content = pd.read_csv(content_path, sep = '\t', header = None)
data_cites = raw_cites.to_numpy()
print(data_cites.shape)
data_content = raw_content.to_numpy()
print(data_content.shape)


(5429, 2)
(2708, 1435)


In [34]:
unique = np.unique(data_cites)
np.sort(unique)
unique.shape
col = raw_content[0].to_numpy()
uniq = np.unique(col)
np.sort(uniq)
index = [x for x in range(0,unique.shape[0])]
dict_cite = dict(zip(unique,index))
reverse_dict = dict(zip(index,unique))
cites = data_cites.copy()
cites
content = data_content.copy()
for i in range(0,cites.shape[0]):
    cites[i][0] = dict_cite[cites[i][0]]
    cites[i][1] = dict_cite[cites[i][1]]
cites
np.savetxt(basedir + 'cora.txt', X=cites, delimiter = ' ', fmt= '%d')
# 恢复
# for i in range(0,cites.shape[0]):
#     cites[i][0] = reverse_dict[cites[i][0]]
#     cites[i][1] = reverse_dict[cites[i][1]]
# cites
# data_cites
# cites == data_cites

array([     35,      40,     114, ..., 1154524, 1154525, 1155073])

(2708,)

array([     35,      40,     114, ..., 1154524, 1154525, 1155073])

array([[     35,    1033],
       [     35,  103482],
       [     35,  103515],
       ...,
       [ 853118, 1140289],
       [ 853155,  853118],
       [ 954315, 1155073]])

array([[   0,   21],
       [   0,  905],
       [   0,  906],
       ...,
       [1874, 2586],
       [1876, 1874],
       [1897, 2707]])